sonar.projectKey=imssolar_pet-clinic
sonar.organization=imssolar

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.source=11
sonar.java.binaries=build/classes/java/main
sonar.sourceEncoding=UTF-8